CREATE TABLE "notifications" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"task_id" varchar,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"type" varchar NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"read_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "task_history" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"user_name" text NOT NULL,
	"user_role" text NOT NULL,
	"action" text NOT NULL,
	"original_message" text,
	"notes" text,
	"status_from" varchar,
	"status_to" varchar,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"assigned_to" text,
	"assigned_to_name" text
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"location" text,
	"room_number" varchar,
	"priority" varchar NOT NULL,
	"status" varchar NOT NULL,
	"created_by" varchar NOT NULL,
	"created_by_name" text NOT NULL,
	"created_by_department" text NOT NULL,
	"operator_id" varchar,
	"operator_name" text,
	"assigned_to" text,
	"assigned_to_name" text,
	"assigned_to_type" varchar,
	"receipt_confirmed_at" timestamp with time zone,
	"receipt_confirmed_by" varchar,
	"receipt_confirmed_by_name" text,
	"sef_id" varchar,
	"sef_name" text,
	"external_company_id" varchar,
	"external_company_name" text,
	"deadline_at" timestamp with time zone,
	"is_overdue" boolean DEFAULT false NOT NULL,
	"estimated_arrival_time" timestamp with time zone,
	"actual_arrival_time" timestamp with time zone,
	"estimated_completion_time" timestamp with time zone,
	"actual_completion_time" timestamp with time zone,
	"time_spent_minutes" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"completed_by" varchar,
	"completed_by_name" text,
	"images" text[],
	"is_recurring" boolean DEFAULT false NOT NULL,
	"recurrence_pattern" varchar DEFAULT 'once',
	"recurrence_end_date" timestamp with time zone,
	"next_occurrence" timestamp with time zone,
	"parent_task_id" varchar,
	"worker_report" text,
	"worker_images" text[]
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"full_name" text NOT NULL,
	"role" varchar NOT NULL,
	"department" text,
	"phone" varchar,
	"password_hash" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"shift" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
